Removed all async code
1c3t3a/rust-socketio pull request #17
Opened 2021-01-31 12:55 UTC by 1c3t3a

During development I've often came across problems related to async rust. When I started the project I thought it would be a nice thing to have the whole crate use rusts async API, but now it just feels like it decreases the development speed. As this is mostly a learning project for me, I think it might be a good idea to refactor the code to be normal, sync rust. We might switch back to async later, when the whole protocol is implemented and the API is fix.

Changes in this PR:

- Removed all async code (originated from the async HTTP requests made via reqwest).
- Changed the callback functions of the socket.io client from `Fn` to `FnMut`, because this allows using the socket within the callback.

2021-01-31 19:03 UTC, Colin1860 requested changes
Looks fine overall. Pls fix the remarks I wrote, I will do some refactoring to assist you! :)

2021-01-31 19:03 UTC, Colin1860 commented on src/socketio/transport.rs
> +                    let mut to_be_removed = Vec::new();
Colin! Refactor this!

2021-01-31 19:03 UTC, Colin1860 commented on src/socketio/transport.rs
> +                                if let Some(function) = clone_self.get_event_callback(&Event::Custom(event)) {
Maybe refactor

2021-02-01 17:16 UTC, 1c3t3a commented on src/socketio/transport.rs
> +            .ok_or(Error::PoisonedLockError)?
Removed it for now, but it would make sense to cover such errors in a designated Error type.

2021-02-01 17:29 UTC, 1c3t3a commented on src/engineio/packet.rs
> +    match b {
I actually switched back to char, I was wrong thinking that this might fail.

2021-02-02 16:35 UTC, Colin1860 commented on src/socketio/transport.rs
> +                                if let Some(function) = clone_self.get_event_callback(&Event::Custom(event)) {
Maybe after some contributions, I'll have another look at this. I still don't love it, but its fine right now

2021-02-02 16:35 UTC, Colin1860 approved these changes

2021-02-02 21:14 UTC, kw-fn reviewed
this looks fine, there is certainly improvements with using try to capture the
errors and not needing to unwrap so many values, the response from the `open`
method is also much simplified and possibly now working with the final failing
decode test, as well improving testing is always a nice step, use of
`PoisonError` is interesting and it might be worthwhile to add some comments
specific to when and how memory is expected to poison, and adding some testing
would be appropriate, in some cases you don't want to poison the variable and
the problem can be caught and recovered from

2021-02-02 21:14 UTC, kw-fn commented on src/engineio/transport.rs
> +    const SERVER_URL: &str = "http://localhost:4201";
again I'm not sure why this is incremented

2021-02-02 21:14 UTC, kw-fn commented on src/socketio/transport.rs
> +    const SERVER_URL: &str = "http://localhost:4200";
this one is different?

2021-02-02 21:14 UTC, kw-fn commented on src/socketio/transport.rs
> +                                        lock(contents[1].to_string());
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on src/socketio/transport.rs
> +                                lock(contents[0].to_string());
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on README.md
> +    socket.emit("foo", payload.to_string()).expect("Server unreachable");
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on README.md
> +    let ack = socket.emit_with_ack("foo", payload.to_string(), Duration::from_secs(2)).unwrap();
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on example/example_engineio.rs
>              "Hello World".to_string().into_bytes(),
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on example/example_engineio.rs
>              "Hello World2".to_string().into_bytes(),
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on example/example_engineio.rs
>          "Hello World3".to_string().into_bytes(),
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on src/engineio/packet.rs
>          assert_eq!(packets[1].data, ("HelloWorld".to_string().into_bytes()));
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on src/engineio/packet.rs
> +        let data = "4Hello\x1e4HelloWorld".to_string().into_bytes();
`.to_owned()` over `.to_string()`

2021-02-02 21:14 UTC, kw-fn commented on src/engineio/transport.rs
> +    const SERVER_URL: &str = "http://localhost:4201";
etc, I think there are too many to tag individually at this point

2021-02-02 21:17 UTC, kw-fn commented on src/socketio/transport.rs
> +                                        lock(contents[1].to_string());
this applies to all cases, I just tagged a few not realizing how many there are

2021-02-03 14:01 UTC, 1c3t3a reviewed
Alright makes sense, I was not aware about the differences between `to_owned` and `to_string`, so thank you for pointing it out.

2021-02-03 14:05 UTC, kw-fn commented
it's actually a lint https://rust-lang.github.io/rust-clippy/master/index.html#str_to_string but
one of the ones you need to select for

2021-02-03 14:09 UTC, 1c3t3a commented
> it's actually a lint https://rust-lang.github.io/rust-clippy/master/index.html#str_to_string but
> one of the ones you need to select for

Ah I See, might make sense to configure a .clippy.toml with lints we find helpful.

2021-02-03 14:10 UTC, 1c3t3a commented
@kw-fn would you like to further investigate the handling of `PoisonError`s?

2021-02-03 14:14 UTC, kw-fn commented
sure I can look into it and add some notes to the docs

2021-02-03 14:17 UTC, merged