fix(engineio): respect pingTimeout and pingInterval to stop connection
1c3t3a/rust-socketio pull request #359
Opened 2023-09-26 09:36 UTC by sirkrypt0

The Engine.IO protocol features a heartbeat mechanism which ensures that the connection between server and client is alive. During that heartbeat, the server sends PINGs to which the client responds with PONGs. Both parties can therefore detect whether the connection is still alive, based on the pingInterval and pingTimeout received in the initial handshake.

However, we previously didn't make use of that in the Engine.IO implementation, which lead to disconnects not being properly recognized.

We now respect these settings and return an error and disconnect the connection, once the pingInterval+pingTimeout time has passed.

See also https://socket.io/docs/v4/how-it-works/#disconnection-detection

Closes #358

2023-09-26 21:28 UTC, ctrlaltf24 requested changes

2023-10-08 15:51 UTC, 1c3t3a reviewed
Thanks a lot for this PR! I would love to merge it after you reacted to @ctrlaltf24's comments, would be great if you could keep the stream impl!

2023-10-08 15:51 UTC, 1c3t3a commented on engineio/src/asynchronous/async_socket.rs
> -        self.generator.poll_next_unpin(cx)
Thanks a lot for this suggestion @ctrlaltf24!! Indeed this is something that I would like to see to not break too many people!

2024-03-31 12:00 UTC, 1c3t3a approved these changes
Decided to land this after all. We're doing a breaking release now anyways and this is a well needed bugfix!

2024-03-31 12:00 UTC, merged